### ISSUE TITLE
Linux Ubuntu 14.04 problem

### ISSUE THREAD

**Issue by charmisuk** [SuperNETorg/Agama#14]
I installed 0.1.2v on Ubuntu 14.04 and had some problems. The iguana kept on freezing on the very first "please wait" page. So i went into /opt/IguanaApp and did ./Iguana and this is what i get for the error.

/opt/IguanaApp/resources/app/assets/bin/linux64/iguana
guiapp listening on port 17777!
======= req.body =======
{ herd: 'iguana' }
it is undefined
iguana flock selected...
selected data: none
{ Error: EACCES: permission denied, unlink '/home/coinguide/.iguana/confs/.tmpmarker'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/home/coinguide/.iguana/confs/.tmpmarker' }
2017-01-29 19:49:36: Launching in no daemon mode
2017-01-29 19:49:36: Error: EACCES: permission denied, open '/home/coinguide/.pm2/pm2.pid'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Daemon.innerStart (/opt/IguanaApp/resources/app/node_modules/pm2/lib/Daemon.js:87:8)
    at /opt/IguanaApp/resources/app/node_modules/pm2/lib/Client.js:76:14
    at /opt/IguanaApp/resources/app/node_modules/pm2/lib/Client.js:273:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any idea on what i should do?

**Comment by satindergrewal** [comment]
solved in slack chat I think. looks permissions issue.
